name: CI/codesize

 

on:
  push:
    branches: main
  pull_request:
    branches: main

 

jobs:
  build:

 

    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: install make
      run: sudo apt-get install make
    - name: install cppcheck
      run: sudo apt-get install cppcheck
    - name: run make
      run: make test
